import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'cash_calculator': 'Cash calculator',
          'cash_counter': 'Cash Counter',
          'history': 'History',
          'calculator': 'Calculator',
          'setting': 'Setting',
          'contact_us': 'Contact Us',
          'privacy_policy': 'Privacy Policy',
          'not': 'Not',
          'credit': 'Credit',
          'debit': 'Debit',
          'save': 'Save',
          'reset': 'Reset',
          'reset_msg': 'Form Reset Successfully',
          'save_msg': 'Your data svaed in history',
          'no_result': 'No results found',
          'theme': 'Theme',
          'darkmode_msg': 'Dark mode enabled',
          'lightmode_msg': 'Light mode enabled',
          'new': 'New',
          'old': 'Old',
          'new_image_msg': 'New cash icons',
          'old_image_msg': 'Old cash icons',
          'images': 'Images',
          'change_img_msg': 'Change Old Not Images',
          'language': 'Language',
          'change_lang_msg': 'Change laanguage',
          'dark_mode': 'Dark Mode',
          'dark_mode_msg': 'Use dark theme for the app'
        },
        'hi_IN': {
          'cash_calculator': 'कैश कैलकुलेटर',
          'cash_counter': 'कैश काउंटर',
          'history': 'इतिहास',
          'calculator': 'कैलकुलेटर',
          'setting': 'सेटिंग',
          'contact_us': 'हमसे संपर्क करें',
          'privacy_policy': 'गोपनीयता नीति',
          'not': 'नोट',
          'credit': 'क्रेडिट',
          'debit': 'डेबिट',
          'save': 'सहेजें',
          'reset': 'रीसेट करें',
          'reset_msg': 'फॉर्म सफलतापूर्वक रीसेट हो गया',
          'save_msg': 'आपका डेटा इतिहास में सहेजा गया',
          'no_result': 'कोई परिणाम नहीं मिला',
          'theme': 'थीम',
          'darkmode_msg': 'डार्क मोड सक्षम',
          'lightmode_msg': 'लाइट मोड सक्षम',
          'new': 'नया',
          'old': 'पुराना',
          'new_image_msg': 'नए कैश आइकन',
          'old_image_msg': 'पुराने कैश आइकन',
          'images': 'तस्वीरें',
          'change_img_msg': 'पुरानी छवि बदलें',
          'language': 'भाषा',
          'change_lang_msg': 'भाषा बदलें',
          'dark_mode': 'डार्क मोड',
          'dark_mode_msg': 'ऐप के लिए डार्क थीम का उपयोग करें',
        },
        'pa_IN': {
          'cash_calculator': 'ਕੈਸ਼ ਕੈਲਕੁਲੇਟਰ',
          'cash_counter': 'ਕੈਸ਼ ਕਾਊਂਟਰ',
          'history': 'ਇਤਿਹਾਸ',
          'calculator': 'ਕੈਲਕੁਲੇਟਰ',
          'setting': 'ਸੈਟਿੰਗ',
          'contact_us': 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
          'privacy_policy': 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
          'not': 'ਨੋਟ',
          'credit': 'ਕ੍ਰੈਡਿਟ',
          'debit': 'ਡੈਬਿਟ',
          'save': 'ਸੇਵ ਕਰੋ',
          'reset': 'ਰੀਸੈਟ ਕਰੋ',
          'reset_msg': 'ਫਾਰਮ ਸਫਲਤਾਪੂਰਵਕ ਰੀਸੈਟ ਹੋ ਗਿਆ',
          'save_msg': 'ਤੁਹਾਡਾ ਡੇਟਾ ਇਤਿਹਾਸ ਵਿੱਚ ਸੇਵ ਕੀਤਾ ਗਿਆ',
          'no_result': 'ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ',
          'theme': 'ਥੀਮ',
          'darkmode_msg': 'ਡਾਰਕ ਮੋਡ ਸਕ੍ਰੀਨ',
          'lightmode_msg': 'ਲਾਈਟ ਮੋਡ ਸਕ੍ਰੀਨ',
          'new': 'ਨਵਾਂ',
          'old': 'ਪੁਰਾਣਾ',
          'new_image_msg': 'ਨਵੀਆਂ ਕੈਸ਼ ਚਿੱਤਰ',
          'old_image_msg': 'ਪੁਰਾਣੀਆਂ ਕੈਸ਼ ਚਿੱਤਰ',
          'images': 'ਤਸਵੀਰਾਂ',
          'change_img_msg': 'ਪੁਰਾਣੀ ਤਸਵੀਰ ਬਦਲੋ',
          'language': 'ਭਾਸ਼ਾ',
          'change_lang_msg': 'ਭਾਸ਼ਾ ਬਦਲੋ',
          'dark_mode': 'ਡਾਰਕ ਮੋਡ',
          'dark_mode_msg': 'ਐਪ ਲਈ ਡਾਰਕ ਥੀਮ ਦੀ ਵਰਤੋਂ ਕਰੋ',
        },
        'bn_BD': {
          'cash_calculator': 'নগদ ক্যালকুলেটর',
          'cash_counter': 'নগদ কাউন্টার',
          'history': 'ইতিহাস',
          'calculator': 'ক্যালকুলেটর',
          'setting': 'সেটিংস',
          'contact_us': 'যোগাযোগ করুন',
          'privacy_policy': 'গোপনীয়তা নীতি',
          'not': 'না',
          'credit': 'ক্রেডিট',
          'debit': 'ডেবিট',
          'save': 'সংরক্ষণ করুন',
          'reset': 'রিসেট',
          'reset_msg': 'ফর্ম সফলভাবে রিসেট হয়েছে',
          'save_msg': 'আপনার ডেটা ইতিহাসে সংরক্ষিত হয়েছে',
          'no_result': 'কোন ফলাফল পাওয়া যায়নি',
          'theme': 'থিম',
          'darkmode_msg': 'ডার্ক মোড সক্রিয়',
          'lightmode_msg': 'লাইট মোড সক্রিয়',
          'new': 'নতুন',
          'old': 'পুরানো',
          'new_image_msg': 'নতুন নগদ চিত্র',
          'old_image_msg': 'পুরানো নগদ চিত্র',
          'images': 'ছবি',
          'change_img_msg': 'পুরানো নোট চিত্র পরিবর্তন করুন',
          'language': 'ভাষা',
          'change_lang_msg': 'ভাষা পরিবর্তন করুন',
          'dark_mode': 'ডার্ক মোড',
          'dark_mode_msg': 'অ্যাপের জন্য ডার্ক থিম ব্যবহার করুন'
        },
        'mr_IN': {
          'cash_calculator': 'कॅश कॅल्क्युलेटर',
          'cash_counter': 'कॅश काउंटर',
          'history': 'इतिहास',
          'calculator': 'कॅल्क्युलेटर',
          'setting': 'सेटिंग',
          'contact_us': 'आमच्याशी संपर्क साधा',
          'privacy_policy': 'गोपनीयता धोरण',
          'not': 'नाही',
          'credit': 'क्रेडिट',
          'debit': 'डेबिट',
          'save': 'जतन करा',
          'reset': 'रीसेट',
          'reset_msg': 'फॉर्म यशस्वीरित्या रीसेट केला',
          'save_msg': 'तुमची माहिती इतिहासात जतन केली गेली आहे',
          'no_result': 'कोणतेही परिणाम सापडले नाहीत',
          'theme': 'थीम',
          'darkmode_msg': 'डार्क मोड सक्षम केला',
          'lightmode_msg': 'लाइट मोड सक्षम केला',
          'new': 'नवीन',
          'old': 'जुने',
          'new_image_msg': 'नवीन कॅश चिन्हे',
          'old_image_msg': 'जुनी कॅश चिन्हे',
          'images': 'प्रतिमा',
          'change_img_msg': 'जुने नोट्स बदलण्यासाठी चिन्हे',
          'language': 'भाषा',
          'change_lang_msg': 'भाषा बदला',
          'dark_mode': 'डार्क मोड',
          'dark_mode_msg': 'अॅपसाठी डार्क थीम वापरा',
        },
        'ta_IN': {
          'cash_calculator': 'பணக் கணிப்பாளர்',
          'cash_counter': 'பணக்கவுன்டர்',
          'history': 'வரலாறு',
          'calculator': 'கணிப்பான்',
          'setting': 'அமைப்புகள்',
          'contact_us': 'எங்களை தொடர்பு கொள்ளவும்',
          'privacy_policy': 'தனியுரிமைக் கொள்கை',
          'not': 'இல்லை',
          'credit': 'கடன்',
          'debit': 'பணவீக்கம்',
          'save': 'சேமி',
          'reset': 'மீட்டமை',
          'reset_msg': 'படிவம் வெற்றிகரமாக மீட்டமைக்கப்பட்டது',
          'save_msg': 'உங்கள் தரவு வரலாற்றில் சேமிக்கப்பட்டது',
          'no_result': 'முடிவுகள் எதுவும் கிடைக்கவில்லை',
          'theme': 'தீம்',
          'darkmode_msg': 'இருண்ட பயன்முறை செயல்படுத்தப்பட்டது',
          'lightmode_msg': 'ஒளி பயன்முறை செயல்படுத்தப்பட்டது',
          'new': 'புதிய',
          'old': 'பழைய',
          'new_image_msg': 'புதிய பண சின்னங்கள்',
          'old_image_msg': 'பழைய பண சின்னங்கள்',
          'images': 'படங்கள்',
          'change_img_msg': 'பழைய நாணய சின்னங்களை மாற்றவும்',
          'language': 'மொழி',
          'change_lang_msg': 'மொழியை மாற்றவும்',
          'dark_mode': 'இருண்ட பயன்முறை',
          'dark_mode_msg': 'யாப்பிற்கு இருண்ட தீமைப் பயன்பாடு'
        },
        'tl_IN': {
          'cash_calculator': 'క్యాష్ కాలిక్యులేటర్',
          'cash_counter': 'క్యాష్ కౌంటర్',
          'history': 'చరిత్ర',
          'calculator': 'కాలిక్యులేటర్',
          'setting': 'సెట్టింగ్',
          'contact_us': 'మమ్మల్ని సంప్రదించండి',
          'privacy_policy': 'గోప్యతా విధానం',
          'not': 'కాదు',
          'credit': 'క్రెడిట్',
          'debit': 'డెబిట్',
          'save': 'సేవ్',
          'reset': 'రీసెట్',
          'reset_msg': 'ఫారమ్ విజయవంతంగా రీసెట్ చేయబడింది',
          'save_msg': 'మీ డేటా చరిత్రలో సేవ్ చేయబడింది',
          'no_result': 'ఫలితాలు కనుగొనబడలేదు',
          'theme': 'థీమ్',
          'darkmode_msg': 'డార్క్ మోడ్ ప్రారంభించబడింది',
          'lightmode_msg': 'లైట్ మోడ్ ప్రారంభించబడింది',
          'new': 'క్రొత్త',
          'old': 'పాత',
          'new_image_msg': 'క్రొత్త నగదు చిహ్నాలు',
          'old_image_msg': 'పాత నగదు చిహ్నాలు',
          'images': 'చిత్రాలు',
          'change_img_msg': 'పాత నోట్ల చిత్రాలను మార్చండి',
          'language': 'భాష',
          'change_lang_msg': 'భాషను మార్చండి',
          'dark_mode': 'డార్క్ మోడ్',
          'dark_mode_msg': 'యాప్ కోసం డార్క్ థీమ్ ఉపయోగించండి'
        }
      };
}
